# Generated by Django 5.2.8 on 2025-11-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('student_email', models.CharField()),
                ('personal_email', models.CharField()),
                ('locker_number', models.IntegerField()),
                ('locker_combination', models.CharField()),
                ('good_student', models.BooleanField()),
            ],
        ),
    ]
